# Generated by Django 5.0.1 on 2024-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_coach', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lien_photo', models.URLField()),
                ('lien_site_internet', models.URLField()),
                ('message_publicite', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
