# Generated by Django 5.0.3 on 2024-03-10 19:48

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_google_sheet', models.URLField(verbose_name='Lien vers la feuille Google Sheets')),
            ],
        ),
    ]
