# Generated by Django 5.0.3 on 2024-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='lien_google_sheet',
            field=models.URLField(verbose_name=''),
        ),
    ]
